### ISSUE TITLE
Assertion failure just before insert

### ISSUE THREAD

**Issue by rgrannell1** [rgrannell1/engram.py#14]
```
INFO:urllib3.connectionpool:Starting new HTTP connection (1): seriot.ch
ERROR:root:title was not a string.
Traceback (most recent call last):
  File "/home/ryan/Code/engram.py/engram/result.py", line 136, in then
    result = fn(self.value)
  File "/home/ryan/Code/engram.py/engram/resave_bookmark.py", line 62, in <lambda>
    .tap(  lambda data:  sql.insert_bookmark(*data) )
  File "/home/ryan/Code/engram.py/engram/sql.py", line 70, in insert_bookmark
    assert isinstance(url,   str),          "url was not a string."
```

**Comment by rgrannell1** [comment]
resolved
