### ISSUE TITLE
Failure in  content-type parsing

### ISSUE THREAD

**Issue by rgrannell1** [rgrannell1/engram.py#15]
```
/api/resave/http://artyom.me/lens-over-tea-1
INFO:urllib3.connectionpool:Starting new HTTP connection (1): artyom.me
ERROR:root:'content-type'
Traceback (most recent call last):
File "/home/ryan/Code/engram.py/engram/result.py", line 136, in then
result = fn(self.value)
File "/home/ryan/Code/engram.py/engram/extract_metadata.py", line 211, in <lambda>
.then(lambda response: extract_title(uri, response))
File "/home/ryan/Code/engram.py/engram/extract_metadata.py", line 172, in extract_title
content_type_result = mimetype.parse(response.headers['content-type'])
File "/usr/lib/python3/dist-packages/requests/structures.py", line 77, in __getitem__
return self._store[key.lower()][1]
KeyError: 'content-type'
```

**Comment by rgrannell1** [comment]
Page doesn't specify a content type; now handled correctly.
