### ISSUE TITLE
Unicode decode error

### ISSUE THREAD

**Issue by rgrannell1** [rgrannell1/engram.py#16]
```
INFO:urllib3.connectionpool:Starting new HTTP connection (1): ww2.it.nuigalway.ie
ERROR:root:'utf-8' codec can't decode byte 0x96 in position 297: invalid start byte
Traceback (most recent call last):
  File "/home/ryan/Code/engram.py/engram/result.py", line 136, in then
    result = fn(self.value)
  File "/home/ryan/Code/engram.py/engram/extract_metadata.py", line 80, in <lambda>
    .then(lambda content: content.decode('utf-8'))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x96 in position 297: invalid start byte
```

**Comment by rgrannell1** [comment]
Failed to replicate.
